name: Bump Semantic Version

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
      - labeled
      - unlabeled
      - closed

jobs:
  # SemVer bumper by labels
  bump:
    runs-on: ubuntu-latest
    steps:
      - id: bump
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
